### ISSUE TITLE
Application route mixin not found

### ISSUE THREAD

**Issue by mzahidriaz** [sir-dunxalot/ember-modals#30]
Ember 2.4.3
Ember-CLI 2.4.3

`import ApplicationRouteMixin from 'ember-modals/mixins/routes/application';`

Migrating from ember 1.X to 2.X I started getting this error.

**Comment by sir-dunxalot** [comment]
As of this addon's `1.0.0` release, which was written for Ember 2.0+, there is no application route mixin. The documentation and setup in the readme has been updated to reflect this. If you're still having issues after updating to `1.0.0` please let me know.

**Comment by mzahidriaz** [comment]
Ok so no need to provide `RouteMixin`, I have working dialog now.
But in previous version I have much more control
I can pass `controller`, `template` and name of the `outlet`
how can we leverage such options in latest version `1.0.0`.

**Comment by mzahidriaz** [comment]
can we use popover style or modal style?

**Comment by sir-dunxalot** [comment]
You use whatever component you want (since Ember 2.0 deprecates views and controllers in favor of components). You will have the same functionality you had before, but it should be in a component. This was a necessary breaking change to keep up with Ember 2.0.

As for outlet, that is not necessary anymore either. The `{{ember-modals}}` component will render all modals in a single place. There is not support for multiple modals outlets anymore but it's something we could add in the future if people are actually using it.

With regards to styling, the styling is still up to you but the library includes a basic stylesheet, like it did before `1.0.0`.

**Comment by sir-dunxalot** [comment]
And you also still have access to the class that rendered the modal - now this is done via the `targetObject` property. See [here](https://github.com/sir-dunxalot/ember-modals#accessing-the-caller-context) for more info.
